spring:
  application:
    name: mail-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:stumpps13@gmail.com}
    password: ${EMAIL_PASSWORD:adigsjcpniwsneqz}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: mailId
      properties:
        spring:
          json:
            type:
              mapping: mailevent:com.example.mailservice.event.MailEvent

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
